# Generated by Django 3.2.4 on 2021-06-05 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Acc_No', models.IntegerField(max_length=200, primary_key=True, serialize=False)),
                ('Account_Holder', models.CharField(max_length=200)),
                ('Email_Id', models.EmailField(max_length=200)),
                ('Current_Balance', models.IntegerField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.IntegerField(default=0)),
                ('credit', models.IntegerField(default=0)),
                ('updated_balance', models.IntegerField(default=0)),
                ('Acc_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.customer')),
            ],
        ),
    ]
