# Generated by Django 3.2.4 on 2021-06-06 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='credit',
            new_name='Receiver_Acc_No',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='debit',
            new_name='amount_transferred',
        ),
    ]
