# Generated by Django 3.2.4 on 2021-06-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20210606_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Receiver_Acc_No',
            new_name='Acc_no_of_reciever',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='Acc_No',
            new_name='Acc_no_of_sender',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='amount_transferred',
            new_name='Amount_transferred',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='updated_balance',
            new_name='Updated_balance_of_sender',
        ),
        migrations.AddField(
            model_name='transaction',
            name='Date_and_time',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='Reciever_name',
            field=models.CharField(max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='Sender_name',
            field=models.CharField(max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_balance_of_reciever',
            field=models.IntegerField(default=0),
        ),
    ]
