# Generated by Django 3.2.4 on 2021-06-10 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_alter_transaction_date_and_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='Date_and_time',
        ),
    ]
