# Generated by Django 3.2.4 on 2021-06-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_remove_transaction_date_and_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='Date_Time',
            field=models.DateTimeField(null=True),
        ),
    ]
