# Generated by Django 3.2.4 on 2021-06-10 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_alter_transaction_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Acc_no_of_sender',
            new_name='Acc_No',
        ),
    ]
